# Netlify Configuration for Workout Timer Pro

[build]
  # Build command - Vite will bundle and optimize the app
  command = "npm run build"

  # Publish directory - where Vite outputs the built files
  publish = "dist"

[functions]
  # Directory containing serverless functions
  directory = "netlify/functions"

# Redirect all requests to index.html for SPA routing (except API/functions)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false  # Don't override existing files or functions

# Headers for PWA and security
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - optimized for YouTube embeds, search, PostHog analytics, icon fonts, and admin dashboard
    # Updated to support multi-layer icon loading: self-hosted fonts + CDN fallback
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src-elem 'self' 'unsafe-inline' https://www.youtube.com https://www.gstatic.com https://cdn.jsdelivr.net https://us-assets.i.posthog.com https://app.posthog.com; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; img-src 'self' data: https: blob:; font-src 'self' data: https://fonts.gstatic.com https://cdn.jsdelivr.net; connect-src 'self' https://www.youtube.com https://www.googleapis.com https://suggestqueries.google.com https://img.youtube.com https://cdn.jsdelivr.net https://us.i.posthog.com https://us-assets.i.posthog.com https://app.posthog.com; frame-src https://www.youtube.com https://www.youtube-nocookie.com; media-src 'self' https://www.youtube.com https://*.googlevideo.com blob:; worker-src 'self' blob:;"

    # Allow embedding YouTube (don't block our own embeds)
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

    # Referrer Policy - YouTube needs this for analytics and embed validation
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Permissions Policy - allow autoplay for YouTube (URLs must be quoted)
    Permissions-Policy = "autoplay=(self \"https://www.youtube.com\" \"https://www.youtube-nocookie.com\"), fullscreen=(self \"https://www.youtube.com\" \"https://www.youtube-nocookie.com\"), picture-in-picture=(self \"https://www.youtube.com\" \"https://www.youtube-nocookie.com\")"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/version.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/json"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment (optional - add if needed)
# [build.environment]
#   NODE_VERSION = "20"
